steps:
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci

  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if npm run | grep -q ' test'; then
          npm test
        else
          echo 'No test script found. Skipping tests.'
        fi

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ldx:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ldx:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        GOOGLE_GENERATIVE_AI_API_KEY_VALUE=$$(gcloud secrets versions access latest --secret=GOOGLE_GENERATIVE_AI_API_KEY)
        NEXT_PUBLIC_SUPABASE_URL_VALUE=$$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_SUPABASE_URL)
        NEXT_PUBLIC_SUPABASE_ANON_KEY_VALUE=$$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_SUPABASE_ANON_KEY)
        SUPABASE_SERVICE_ROLE_KEY_VALUE=$$(gcloud secrets versions access latest --secret=SUPABASE_SERVICE_ROLE_KEY)
        gcloud run deploy ldx \
          --image=gcr.io/$PROJECT_ID/ldx:$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="GOOGLE_GENERATIVE_AI_API_KEY=$$GOOGLE_GENERATIVE_AI_API_KEY_VALUE,NEXT_PUBLIC_SUPABASE_URL=$$NEXT_PUBLIC_SUPABASE_URL_VALUE,NEXT_PUBLIC_SUPABASE_ANON_KEY=$$NEXT_PUBLIC_SUPABASE_ANON_KEY_VALUE,SUPABASE_SERVICE_ROLE_KEY=$$SUPABASE_SERVICE_ROLE_KEY_VALUE"

images:
  - 'gcr.io/$PROJECT_ID/ldx:$COMMIT_SHA'
